import {
  faUserPlus,
  faUsers,
  faComputer,
  faBookOpen,
  faCalendarAlt,
  faPenFancy,
  faCog,
  faBook,
} from "@fortawesome/free-solid-svg-icons";

export const cards = [
  {
    id: 1,
    Heading: "Profile",
    link: "Profile",
    isImg: true,
    color1: "#4F1A60",
    color2: "#f5f5f5",
    roles: ["admin", "teacher"],
  },
  {
    id: 2,
    Heading: "Add User",
    link: "Adduser",
    isImg: false,
    Icon: faUserPlus,
    color1: "#FDDE09",
    color2: "#f5f5f5",
    roles: ["admin"],
  },
  {
    id: 3,
    Heading: "List Users",
    link: "ListUsers",
    isImg: false,
    Icon: faUsers,
    color1: "#E40070",
    color2: "#f5f5f5",
    roles: ["admin"],
  },
  {
    id: 4,
    Heading: "Admissions",
    link: "Admissions",
    isImg: false,
    Icon: faComputer,
    color1: "#22b508",
    color2: "#f5f5f5",
    roles: ["admin", "clerk"],
  },
  {
    id: 5,
    Heading: "Subject Allocation",
    link: "SubjectAllocation",
    isImg: false,
    Icon: faBookOpen,
    color1: "#CA4DFF",
    color2: "#f5f5f5",
    roles: ["hod"],
  },
  {
    id: 6,
    Heading: "Attendance",
    link: "Attendance",
    isImg: false,
    Icon: faCalendarAlt,
    color1: "#007BFF",
    color2: "#f5f5f5",
    roles: ["teacher"],
  },
  {
    id: 7,
    Heading: "Enter Marks",
    link: "EnterMarks",
    isImg: false,
    Icon: faPenFancy,
    color1: "#6A0DAD",
    color2: "#F3E8FF",
    roles: ["teacher"],
  },
  {
    id: 8,
    Heading: "Subjects",
    link: "Subjects",
    isImg: false,
    Icon: faBook,
    color1: "#F97316",
    color2: "#FFF7ED",
    roles: ["hod"],
  },
  {
    id: 9,
    Heading: "Settings",
    link: "Settings",
    isImg: false,
    Icon: faCog,
    color1: "#09FDEE",
    color2: "#f5f5f5",
    roles: ["admin", "teacher"],
  },
];

export const rolesArray = [
  "Office Secretary",
  "Assistant",
  "Clerk",
  "Peon",
  "Supervisor",
  "Admin",
  "HR Officer",
  "Accountant",
  "IT Support",
  "Librarian",
  "Teacher",
  "HOD",
];
