export const initialAttendance = [
  {
    rollNo: "BSCS-001",
    name: "Ali Raza",
    attendance: [
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-002",
    name: "Aqib Ali",
    attendance: [
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-003",
    name: "Hassan Ahmed",
    attendance: [
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-004",
    name: "Bilal Khan",
    attendance: [
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-005",
    name: "Zain Shah",
    attendance: [
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-006",
    name: "Umair Sheikh",
    attendance: [
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-007",
    name: "Sana Tariq",
    attendance: [
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-008",
    name: "Fatima Noor",
    attendance: [
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-009",
    name: "Hamza Yousuf",
    attendance: [
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-010",
    name: "Ayesha Khan",
    attendance: [
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  // 🟢 Remaining 20 students (BSCS-011 to BSCS-030)
  {
    rollNo: "BSCS-011",
    name: "Ahmed Ali",
    attendance: [
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-012",
    name: "Maria Iqbal",
    attendance: [
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-013",
    name: "Shahid Mehmood",
    attendance: [
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-014",
    name: "Eman Fatima",
    attendance: [
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-015",
    name: "Noor Ahmed",
    attendance: [
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-016",
    name: "Ibrahim Khan",
    attendance: [
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-017",
    name: "Rida Hasan",
    attendance: [
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-018",
    name: "Hassan Raza",
    attendance: [
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-019",
    name: "Sara Naveed",
    attendance: [
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-020",
    name: "Kamran Ali",
    attendance: [
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-021",
    name: "Hina Fatima",
    attendance: [
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-022",
    name: "Owais Sheikh",
    attendance: [
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Present",
      "Absent",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-023",
    name: "Mahnoor Tariq",
    attendance: [
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-024",
    name: "Adeel Rehman",
    attendance: [
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-025",
    name: "Fizza Imran",
    attendance: [
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-026",
    name: "Shahzaib Khan",
    attendance: [
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-027",
    name: "Khadija Noor",
    attendance: [
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-028",
    name: "Imran Qureshi",
    attendance: [
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-029",
    name: "Nimra Aslam",
    attendance: [
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
  {
    rollNo: "BSCS-030",
    name: "Faizan Malik",
    attendance: [
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
      "Absent",
      "Absent",
      "Absent",
      "Present",
      "Absent",
    ],
    get percentage() {
      return (
        (this.attendance.filter((d) => d === "Present").length /
          this.attendance.length) *
        100
      );
    },
  },
];
