// Hooks/useRecivedForm.js
import { useState, useMemo } from "react";

export default function useRecivedForm({ initial = [], pageSize = 10 }) {
  const [query, setQuery] = useState("");
  const [page, setPage] = useState(1);
  const [sort, setSort] = useState({ key: "", dir: "asc" });

  // Filter + sort
  const filtered = useMemo(() => {
    let data = [...initial];
    if (query) {
      data = data.filter((item) =>
        Object.values(item)
          .join(" ")
          .toLowerCase()
          .includes(query.toLowerCase())
      );
    }
    if (sort.key) {
      data.sort((a, b) => {
        if (a[sort.key] < b[sort.key]) return sort.dir === "asc" ? -1 : 1;
        if (a[sort.key] > b[sort.key]) return sort.dir === "asc" ? 1 : -1;
        return 0;
      });
    }
    return data;
  }, [initial, query, sort]);

  const pageCount = Math.ceil(filtered.length / pageSize) || 1;
  const rows = filtered.slice((page - 1) * pageSize, page * pageSize);

  const onSort = (key) =>
    setSort((prev) => ({
      key,
      dir: prev.key === key && prev.dir === "asc" ? "desc" : "asc",
    }));

  return { rows, page, pageCount, setPage, query, setQuery, sort, onSort };
}

export const initialForms = [
  {
    serialNo: 1,
    studentName: "Mohtashim Khattak",
    fatherName: "Shabbir Ansari",
    department: "English Language And Literature",
    cnic: "42101-1000085-6",
    status: "Revert",
  },
  {
    serialNo: 2,
    studentName: "Tariq Khattak",
    fatherName: "Ali Farooqi",
    department: "English Language And Literature",
    cnic: "42101-1000102-2",
    status: "Pending",
  },
  {
    serialNo: 3,
    studentName: "Hamza Mirza",
    fatherName: "Bilal Mirza",
    department: "English Language And Literature",
    cnic: "42101-1000127-7",
    status: "Pending",
  },
  {
    serialNo: 4,
    studentName: "Mohtashim Memon",
    fatherName: "Waqar Zubair",
    department: "Computer Science",
    cnic: "42101-1000063-4",
    status: "Approved",
  },
  {
    serialNo: 5,
    studentName: "Ahmed Hashmi",
    fatherName: "Imran Farooqi",
    department: "Business Administration",
    cnic: "42101-1000154-4",
    status: "Pending",
  },
  {
    serialNo: 6,
    studentName: "Junaid Mirza",
    fatherName: "Ameen Shah",
    department: "Computer Science",
    cnic: "42101-1000081-2",
    status: "Approved",
  },
  {
    serialNo: 7,
    studentName: "Asad Malik",
    fatherName: "Shabbir Zubair",
    department: "Business Administration",
    cnic: "42101-1000083-4",
    status: "Trash",
  },
  {
    serialNo: 8,
    studentName: "Mohtashim Hussain",
    fatherName: "Shahid Farooqi",
    department: "English Language And Literature",
    cnic: "42101-1000067-8",
    status: "Revert",
  },
  {
    serialNo: 9,
    studentName: "Hassan Malik",
    fatherName: "Abdul Qureshi",
    department: "Business Administration",
    cnic: "42101-1000008-9",
    status: "Trash",
  },
  {
    serialNo: 10,
    studentName: "Noman Ansari",
    fatherName: "Ameen Zubair",
    department: "English Language And Literature",
    cnic: "42101-1000028-9",
    status: "Revert",
  },
  {
    serialNo: 11,
    studentName: "Imran Farooqi",
    fatherName: "Danish Ansari",
    department: "English Language And Literature",
    cnic: "42101-1000131-1",
    status: "Pending",
  },
  {
    serialNo: 12,
    studentName: "Junaid Shaikh",
    fatherName: "Zafar Qureshi",
    department: "English Language And Literature",
    cnic: "42101-1000061-2",
    status: "Revert",
  },
  {
    serialNo: 13,
    studentName: "Danish Khattak",
    fatherName: "Zafar Rehman",
    department: "Business Administration",
    cnic: "42101-1000089-0",
    status: "Trash",
  },
  {
    serialNo: 14,
    studentName: "Danish Zubair",
    fatherName: "Saleem Shaikh",
    department: "Business Administration",
    cnic: "42101-1000080-1",
    status: "Trash",
  },
  {
    serialNo: 15,
    studentName: "Ahmed Hussain",
    fatherName: "Sami Qureshi",
    department: "English Language And Literature",
    cnic: "42101-1000146-6",
    status: "Pending",
  },
  {
    serialNo: 16,
    studentName: "Aqib Sheikh",
    fatherName: "Ghulam Chaudhry",
    department: "Business Administration",
    cnic: "42101-1000056-7",
    status: "Trash",
  },
  {
    serialNo: 17,
    studentName: "Danish Raza",
    fatherName: "Bashir Khan",
    department: "Computer Science",
    cnic: "42101-1000042-3",
    status: "Approved",
  },
  {
    serialNo: 18,
    studentName: "Hassan Hashmi",
    fatherName: "Bashir Chaudhry",
    department: "Business Administration",
    cnic: "42101-1000059-0",
    status: "Trash",
  },
  {
    serialNo: 19,
    studentName: "Hassan Shah",
    fatherName: "Shabbir Malik",
    department: "Computer Science",
    cnic: "42101-1000045-6",
    status: "Approved",
  },
  {
    serialNo: 20,
    studentName: "Usman Khan",
    fatherName: "Ali Butt",
    department: "English Language And Literature",
    cnic: "42101-1000109-9",
    status: "Pending",
  },
  {
    serialNo: 21,
    studentName: "Danish Raza",
    fatherName: "Muhammad Ansari",
    department: "Computer Science",
    cnic: "42101-1000096-7",
    status: "Approved",
  },
  {
    serialNo: 22,
    studentName: "Asad Khan",
    fatherName: "Abdul Khan",
    department: "Business Administration",
    cnic: "42101-1000011-2",
    status: "Trash",
  },
  {
    serialNo: 23,
    studentName: "Hassan Butt",
    fatherName: "Junaid Raza",
    department: "Computer Science",
    cnic: "42101-1000108-8",
    status: "Pending",
  },
  {
    serialNo: 24,
    studentName: "Bilal Khattak",
    fatherName: "Imtiaz Memon",
    department: "Computer Science",
    cnic: "42101-1000012-3",
    status: "Approved",
  },
  {
    serialNo: 25,
    studentName: "Junaid Malik",
    fatherName: "Usman Qureshi",
    department: "Computer Science",
    cnic: "42101-1000160-0",
    status: "Pending",
  },
  {
    serialNo: 26,
    studentName: "Kashif Chaudhry",
    fatherName: "Saleem Raza",
    department: "English Language And Literature",
    cnic: "42101-1000088-9",
    status: "Revert",
  },
  {
    serialNo: 27,
    studentName: "Luqman Raza",
    fatherName: "Imran Khan",
    department: "Computer Science",
    cnic: "42101-1000141-1",
    status: "Pending",
  },
  {
    serialNo: 28,
    studentName: "Luqman Memon",
    fatherName: "Saleem Qureshi",
    department: "Business Administration",
    cnic: "42101-1000005-6",
    status: "Trash",
  },
  {
    serialNo: 29,
    studentName: "Ahmed Hashmi",
    fatherName: "Danish Mirza",
    department: "English Language And Literature",
    cnic: "42101-1000149-9",
    status: "Pending",
  },
  {
    serialNo: 30,
    studentName: "Kamran Shaikh",
    fatherName: "Luqman Ansari",
    department: "Business Administration",
    cnic: "42101-1000132-2",
    status: "Pending",
  },
  {
    serialNo: 31,
    studentName: "Sami Butt",
    fatherName: "Usman Khan",
    department: "English Language And Literature",
    cnic: "42101-1000123-3",
    status: "Pending",
  },
  {
    serialNo: 32,
    studentName: "Ahmed Chaudhry",
    fatherName: "Mazhar Hashmi",
    department: "Business Administration",
    cnic: "42101-1000032-3",
    status: "Trash",
  },
  {
    serialNo: 33,
    studentName: "Ali Qureshi",
    fatherName: "Imran Memon",
    department: "Computer Science",
    cnic: "42101-1000162-2",
    status: "Pending",
  },
  {
    serialNo: 34,
    studentName: "Junaid Raza",
    fatherName: "Bilal Memon",
    department: "English Language And Literature",
    cnic: "42101-1000155-5",
    status: "Pending",
  },
  {
    serialNo: 35,
    studentName: "Asad Farooqi",
    fatherName: "Asad Ansari",
    department: "English Language And Literature",
    cnic: "42101-1000125-5",
    status: "Pending",
  },
  {
    serialNo: 36,
    studentName: "Tariq Memon",
    fatherName: "Ghulam Chaudhry",
    department: "Business Administration",
    cnic: "42101-1000074-5",
    status: "Trash",
  },
  {
    serialNo: 37,
    studentName: "Kashif Farooqi",
    fatherName: "Iftikhar Abbasi",
    department: "English Language And Literature",
    cnic: "42101-1000037-8",
    status: "Revert",
  },
  {
    serialNo: 38,
    studentName: "Usman Hussain",
    fatherName: "Asad Butt",
    department: "Computer Science",
    cnic: "42101-1000106-6",
    status: "Pending",
  },
  {
    serialNo: 39,
    studentName: "Ahmed Khan",
    fatherName: "Hafiz Butt",
    department: "Computer Science",
    cnic: "42101-1000066-7",
    status: "Approved",
  },
  {
    serialNo: 40,
    studentName: "Danish Farooqi",
    fatherName: "Kamran Mirza",
    department: "Computer Science",
    cnic: "42101-1000167-7",
    status: "Pending",
  },
  {
    serialNo: 41,
    studentName: "Asad Khan",
    fatherName: "Abdul Shah",
    department: "English Language And Literature",
    cnic: "42101-1000022-3",
    status: "Revert",
  },
  {
    serialNo: 42,
    studentName: "Bilal Sheikh",
    fatherName: "Hafiz Raza",
    department: "Computer Science",
    cnic: "42101-1000087-8",
    status: "Approved",
  },
  {
    serialNo: 43,
    studentName: "Sami Mirza",
    fatherName: "Iftikhar Rehman",
    department: "Computer Science",
    cnic: "42101-1000051-2",
    status: "Approved",
  },
  {
    serialNo: 44,
    studentName: "Danish Hussain",
    fatherName: "Ali Chaudhry",
    department: "Computer Science",
    cnic: "42101-1000114-4",
    status: "Pending",
  },
  {
    serialNo: 45,
    studentName: "Asad Memon",
    fatherName: "Ameen Rehman",
    department: "Business Administration",
    cnic: "42101-1000029-0",
    status: "Trash",
  },
  {
    serialNo: 46,
    studentName: "Junaid Bhatti",
    fatherName: "Danish Butt",
    department: "Computer Science",
    cnic: "42101-1000139-9",
    status: "Pending",
  },
  {
    serialNo: 47,
    studentName: "Ali Farooqi",
    fatherName: "Rashid Shah",
    department: "English Language And Literature",
    cnic: "42101-1000007-8",
    status: "Revert",
  },
  {
    serialNo: 48,
    studentName: "Kashif Malik",
    fatherName: "Rashid Bhatti",
    department: "English Language And Literature",
    cnic: "42101-1000049-0",
    status: "Revert",
  },
  {
    serialNo: 49,
    studentName: "Bilal Shaikh",
    fatherName: "Ali Raza",
    department: "Business Administration",
    cnic: "42101-1000157-7",
    status: "Pending",
  },
  {
    serialNo: 50,
    studentName: "Asad Khan",
    fatherName: "Sajid Khattak",
    department: "English Language And Literature",
    cnic: "42101-1000070-1",
    status: "Revert",
  },
  {
    serialNo: 51,
    studentName: "Hassan Malik",
    fatherName: "Tariq Hussain",
    department: "English Language And Literature",
    cnic: "42101-1000140-0",
    status: "Pending",
  },
  {
    serialNo: 52,
    studentName: "Sami Bhatti",
    fatherName: "Ameen Farooqi",
    department: "Computer Science",
    cnic: "42101-1000003-4",
    status: "Approved",
  },
  {
    serialNo: 53,
    studentName: "Danish Chaudhry",
    fatherName: "Asad Memon",
    department: "Computer Science",
    cnic: "42101-1000104-4",
    status: "Pending",
  },
  {
    serialNo: 54,
    studentName: "Kamran Qureshi",
    fatherName: "Rashid Khattak",
    department: "Computer Science",
    cnic: "42101-1000057-8",
    status: "Approved",
  },
  {
    serialNo: 55,
    studentName: "Bilal Hashmi",
    fatherName: "Danish Hussain",
    department: "Business Administration",
    cnic: "42101-1000100-0",
    status: "Pending",
  },
  {
    serialNo: 56,
    studentName: "Noman Shaikh",
    fatherName: "Kamran Raza",
    department: "Computer Science",
    cnic: "42101-1000143-3",
    status: "Pending",
  },
  {
    serialNo: 57,
    studentName: "Noman Khan",
    fatherName: "Mazhar Butt",
    department: "English Language And Literature",
    cnic: "42101-1000058-9",
    status: "Revert",
  },
  {
    serialNo: 58,
    studentName: "Mohtashim Hussain",
    fatherName: "Imtiaz Butt",
    department: "Computer Science",
    cnic: "42101-1000099-0",
    status: "Approved",
  },
  {
    serialNo: 59,
    studentName: "Junaid Butt",
    fatherName: "Iftikhar Ansari",
    department: "English Language And Literature",
    cnic: "42101-1000055-6",
    status: "Revert",
  },
  {
    serialNo: 60,
    studentName: "Ahmed Qureshi",
    fatherName: "Hamza Farooqi",
    department: "Business Administration",
    cnic: "42101-1000101-1",
    status: "Pending",
  },
  {
    serialNo: 61,
    studentName: "Usman Farooqi",
    fatherName: "Latif Abbasi",
    department: "Business Administration",
    cnic: "42101-1000041-2",
    status: "Trash",
  },
  {
    serialNo: 62,
    studentName: "Hamza Memon",
    fatherName: "Ghulam Hussain",
    department: "Computer Science",
    cnic: "42101-1000018-9",
    status: "Approved",
  },
  {
    serialNo: 63,
    studentName: "Kashif Shaikh",
    fatherName: "Shabbir Abbasi",
    department: "English Language And Literature",
    cnic: "42101-1000094-5",
    status: "Revert",
  },
  {
    serialNo: 64,
    studentName: "Sami Khattak",
    fatherName: "Syed Chaudhry",
    department: "Computer Science",
    cnic: "42101-1000093-4",
    status: "Approved",
  },
  {
    serialNo: 65,
    studentName: "Usman Shaikh",
    fatherName: "Abdul Raza",
    department: "Computer Science",
    cnic: "42101-1000015-6",
    status: "Approved",
  },
  {
    serialNo: 66,
    studentName: "Aqib Farooqi",
    fatherName: "Yasir Hussain",
    department: "Business Administration",
    cnic: "42101-1000086-7",
    status: "Trash",
  },
  {
    serialNo: 67,
    studentName: "Kashif Hashmi",
    fatherName: "Syed Shaikh",
    department: "Computer Science",
    cnic: "42101-1000069-0",
    status: "Approved",
  },
  {
    serialNo: 68,
    studentName: "Junaid Qureshi",
    fatherName: "Syed Farooqi",
    department: "Business Administration",
    cnic: "42101-1000065-6",
    status: "Trash",
  },
  {
    serialNo: 69,
    studentName: "Usman Khattak",
    fatherName: "Danish Hashmi",
    department: "English Language And Literature",
    cnic: "42101-1000124-4",
    status: "Pending",
  },
  {
    serialNo: 70,
    studentName: "Fahad Sheikh",
    fatherName: "Iftikhar Chaudhry",
    department: "English Language And Literature",
    cnic: "42101-1000013-4",
    status: "Revert",
  },
  {
    serialNo: 71,
    studentName: "Imran Malik",
    fatherName: "Sami Chaudhry",
    department: "Business Administration",
    cnic: "42101-1000116-6",
    status: "Pending",
  },
  {
    serialNo: 72,
    studentName: "Danish Qureshi",
    fatherName: "Waqar Zubair",
    department: "English Language And Literature",
    cnic: "42101-1000073-4",
    status: "Revert",
  },
  {
    serialNo: 73,
    studentName: "Hassan Sheikh",
    fatherName: "Shabbir Raza",
    department: "Business Administration",
    cnic: "42101-1000092-3",
    status: "Trash",
  },
  {
    serialNo: 74,
    studentName: "Imran Chaudhry",
    fatherName: "Tariq Khattak",
    department: "English Language And Literature",
    cnic: "42101-1000161-1",
    status: "Pending",
  },
  {
    serialNo: 75,
    studentName: "Imran Mirza",
    fatherName: "Sami Hussain",
    department: "Business Administration",
    cnic: "42101-1000166-6",
    status: "Pending",
  },
  {
    serialNo: 76,
    studentName: "Junaid Qureshi",
    fatherName: "Kamran Malik",
    department: "Business Administration",
    cnic: "42101-1000159-9",
    status: "Pending",
  },
  {
    serialNo: 77,
    studentName: "Danish Bhatti",
    fatherName: "Waqar Shaikh",
    department: "English Language And Literature",
    cnic: "42101-1000064-5",
    status: "Revert",
  },
  {
    serialNo: 78,
    studentName: "Asad Mirza",
    fatherName: "Iftikhar Ansari",
    department: "Business Administration",
    cnic: "42101-1000035-6",
    status: "Trash",
  },
  {
    serialNo: 79,
    studentName: "Hassan Hashmi",
    fatherName: "Ali Chaudhry",
    department: "Business Administration",
    cnic: "42101-1000118-8",
    status: "Pending",
  },
  {
    serialNo: 80,
    studentName: "Kamran Raza",
    fatherName: "Luqman Butt",
    department: "Computer Science",
    cnic: "42101-1000130-0",
    status: "Pending",
  },
  {
    serialNo: 81,
    studentName: "Hassan Rehman",
    fatherName: "Waqar Shah",
    department: "English Language And Literature",
    cnic: "42101-1000076-7",
    status: "Revert",
  },
  {
    serialNo: 82,
    studentName: "Danish Sheikh",
    fatherName: "Yasir Farooqi",
    department: "Business Administration",
    cnic: "42101-1000062-3",
    status: "Trash",
  },
  {
    serialNo: 83,
    studentName: "Hassan Qureshi",
    fatherName: "Ahmed Hussain",
    department: "English Language And Literature",
    cnic: "42101-1000107-7",
    status: "Pending",
  },
  {
    serialNo: 84,
    studentName: "Kamran Khattak",
    fatherName: "Bilal Mirza",
    department: "Computer Science",
    cnic: "42101-1000151-1",
    status: "Pending",
  },
  {
    serialNo: 85,
    studentName: "Luqman Bhatti",
    fatherName: "Tariq Farooqi",
    department: "Computer Science",
    cnic: "42101-1000113-3",
    status: "Pending",
  },
  {
    serialNo: 86,
    studentName: "Sami Ansari",
    fatherName: "Tariq Raza",
    department: "English Language And Literature",
    cnic: "42101-1000121-1",
    status: "Pending",
  },
  {
    serialNo: 87,
    studentName: "Luqman Chaudhry",
    fatherName: "Kamran Chaudhry",
    department: "Computer Science",
    cnic: "42101-1000134-4",
    status: "Pending",
  },
  {
    serialNo: 88,
    studentName: "Hamza Raza",
    fatherName: "Bashir Butt",
    department: "Computer Science",
    cnic: "42101-1000009-0",
    status: "Approved",
  },
  {
    serialNo: 89,
    studentName: "Tariq Raza",
    fatherName: "Kamran Khattak",
    department: "Business Administration",
    cnic: "42101-1000120-0",
    status: "Pending",
  },
  {
    serialNo: 90,
    studentName: "Kamran Butt",
    fatherName: "Asad Hashmi",
    department: "Business Administration",
    cnic: "42101-1000148-8",
    status: "Pending",
  },
  {
    serialNo: 91,
    studentName: "Sami Shah",
    fatherName: "Shahid Chaudhry",
    department: "Business Administration",
    cnic: "42101-1000098-9",
    status: "Trash",
  },
  {
    serialNo: 92,
    studentName: "Junaid Qureshi",
    fatherName: "Latif Memon",
    department: "Business Administration",
    cnic: "42101-1000020-1",
    status: "Trash",
  },
  {
    serialNo: 93,
    studentName: "Ahmed Sheikh",
    fatherName: "Muhammad Khattak",
    department: "English Language And Literature",
    cnic: "42101-1000079-0",
    status: "Revert",
  },
  {
    serialNo: 94,
    studentName: "Asad Sheikh",
    fatherName: "Imtiaz Hashmi",
    department: "Computer Science",
    cnic: "42101-1000024-5",
    status: "Approved",
  },
  {
    serialNo: 95,
    studentName: "Luqman Mirza",
    fatherName: "Ahmed Hussain",
    department: "Computer Science",
    cnic: "42101-1000153-3",
    status: "Pending",
  },
  {
    serialNo: 96,
    studentName: "Imran Shaikh",
    fatherName: "Nisar Shah",
    department: "Computer Science",
    cnic: "42101-1000030-1",
    status: "Approved",
  },
  {
    serialNo: 97,
    studentName: "Kamran Khan",
    fatherName: "Tariq Khattak",
    department: "English Language And Literature",
    cnic: "42101-1000168-8",
    status: "Pending",
  },
  {
    serialNo: 98,
    studentName: "Hassan Hussain",
    fatherName: "Danish Raza",
    department: "Business Administration",
    cnic: "42101-1000129-9",
    status: "Pending",
  },
  {
    serialNo: 99,
    studentName: "Noman Bhatti",
    fatherName: "Muhammad Hussain",
    department: "English Language And Literature",
    cnic: "42101-1000001-2",
    status: "Revert",
  },
  {
    serialNo: 100,
    studentName: "Ali Butt",
    fatherName: "Bashir Sheikh",
    department: "Computer Science",
    cnic: "42101-1000054-5",
    status: "Approved",
  },
  {
    serialNo: 101,
    studentName: "Luqman Chaudhry",
    fatherName: "Waqar Khattak",
    department: "Business Administration",
    cnic: "42101-1000017-8",
    status: "Trash",
  },
  {
    serialNo: 102,
    studentName: "Kamran Khan",
    fatherName: "Ghulam Raza",
    department: "Computer Science",
    cnic: "42101-1000060-1",
    status: "Approved",
  },
  {
    serialNo: 103,
    studentName: "Fahad Hussain",
    fatherName: "Latif Shah",
    department: "Business Administration",
    cnic: "42101-1000002-3",
    status: "Trash",
  },
  {
    serialNo: 104,
    studentName: "Bilal Khan",
    fatherName: "Saleem Qureshi",
    department: "Computer Science",
    cnic: "42101-1000075-6",
    status: "Approved",
  },
  {
    serialNo: 105,
    studentName: "Hassan Hussain",
    fatherName: "Ali Mirza",
    department: "Business Administration",
    cnic: "42101-1000163-3",
    status: "Pending",
  },
  {
    serialNo: 106,
    studentName: "Usman Mirza",
    fatherName: "Muhammad Zubair",
    department: "Business Administration",
    cnic: "42101-1000014-5",
    status: "Trash",
  },
  {
    serialNo: 107,
    studentName: "Asad Malik",
    fatherName: "Bilal Raza",
    department: "English Language And Literature",
    cnic: "42101-1000152-2",
    status: "Pending",
  },
  {
    serialNo: 108,
    studentName: "Danish Hussain",
    fatherName: "Waqar Shah",
    department: "Computer Science",
    cnic: "42101-1000078-9",
    status: "Approved",
  },
  {
    serialNo: 109,
    studentName: "Luqman Khan",
    fatherName: "Ameen Shaikh",
    department: "English Language And Literature",
    cnic: "42101-1000091-2",
    status: "Revert",
  },
  {
    serialNo: 110,
    studentName: "Noman Khan",
    fatherName: "Muhammad Khattak",
    department: "Computer Science",
    cnic: "42101-1000084-5",
    status: "Approved",
  },
  {
    serialNo: 111,
    studentName: "Bilal Hussain",
    fatherName: "Ali Mirza",
    department: "English Language And Literature",
    cnic: "42101-1000164-4",
    status: "Pending",
  },
  {
    serialNo: 112,
    studentName: "Luqman Raza",
    fatherName: "Syed Abbasi",
    department: "English Language And Literature",
    cnic: "42101-1000043-4",
    status: "Revert",
  },
  {
    serialNo: 113,
    studentName: "Aqib Ansari",
    fatherName: "Ghulam Raza",
    department: "Computer Science",
    cnic: "42101-1000021-2",
    status: "Approved",
  },
  {
    serialNo: 114,
    studentName: "Sami Farooqi",
    fatherName: "Danish Khattak",
    department: "English Language And Literature",
    cnic: "42101-1000142-2",
    status: "Pending",
  },
  {
    serialNo: 115,
    studentName: "Ali Zubair",
    fatherName: "Ameen Butt",
    department: "Business Administration",
    cnic: "42101-1000047-8",
    status: "Trash",
  },
  {
    serialNo: 116,
    studentName: "Sami Khan",
    fatherName: "Imtiaz Malik",
    department: "Computer Science",
    cnic: "42101-1000000-1",
    status: "Approved",
  },
  {
    serialNo: 117,
    studentName: "Noman Shaikh",
    fatherName: "Luqman Malik",
    department: "Business Administration",
    cnic: "42101-1000165-5",
    status: "Pending",
  },
  {
    serialNo: 118,
    studentName: "Sami Shaikh",
    fatherName: "Asad Mirza",
    department: "English Language And Literature",
    cnic: "42101-1000122-2",
    status: "Pending",
  },
  {
    serialNo: 119,
    studentName: "Noman Malik",
    fatherName: "Junaid Ansari",
    department: "Business Administration",
    cnic: "42101-1000126-6",
    status: "Pending",
  },
  {
    serialNo: 120,
    studentName: "Hamza Farooqi",
    fatherName: "Danish Hussain",
    department: "English Language And Literature",
    cnic: "42101-1000144-4",
    status: "Pending",
  },
  {
    serialNo: 121,
    studentName: "Mohtashim Memon",
    fatherName: "Saleem Raza",
    department: "Computer Science",
    cnic: "42101-1000036-7",
    status: "Approved",
  },
  {
    serialNo: 122,
    studentName: "Luqman Khan",
    fatherName: "Kamran Shaikh",
    department: "Business Administration",
    cnic: "42101-1000112-2",
    status: "Pending",
  },
  {
    serialNo: 123,
    studentName: "Tariq Farooqi",
    fatherName: "Danish Qureshi",
    department: "English Language And Literature",
    cnic: "42101-1000158-8",
    status: "Pending",
  },
  {
    serialNo: 124,
    studentName: "Noman Memon",
    fatherName: "Asad Ansari",
    department: "Computer Science",
    cnic: "42101-1000136-6",
    status: "Pending",
  },
  {
    serialNo: 125,
    studentName: "Junaid Raza",
    fatherName: "Ahmed Mirza",
    department: "Computer Science",
    cnic: "42101-1000169-9",
    status: "Pending",
  },
  {
    serialNo: 126,
    studentName: "Bilal Raza",
    fatherName: "Rashid Butt",
    department: "Computer Science",
    cnic: "42101-1000039-0",
    status: "Approved",
  },
  {
    serialNo: 127,
    studentName: "Asad Shaikh",
    fatherName: "Hamza Farooqi",
    department: "Business Administration",
    cnic: "42101-1000103-3",
    status: "Pending",
  },
  {
    serialNo: 128,
    studentName: "Asad Rehman",
    fatherName: "Bashir Shaikh",
    department: "Business Administration",
    cnic: "42101-1000023-4",
    status: "Trash",
  },
  {
    serialNo: 129,
    studentName: "Danish Ansari",
    fatherName: "Shahid Hashmi",
    department: "English Language And Literature",
    cnic: "42101-1000040-1",
    status: "Revert",
  },
  {
    serialNo: 130,
    studentName: "Ahmed Raza",
    fatherName: "Mazhar Khattak",
    department: "Computer Science",
    cnic: "42101-1000072-3",
    status: "Approved",
  },
  {
    serialNo: 131,
    studentName: "Luqman Ansari",
    fatherName: "Ghulam Chaudhry",
    department: "English Language And Literature",
    cnic: "42101-1000097-8",
    status: "Revert",
  },
  {
    serialNo: 132,
    studentName: "Junaid Memon",
    fatherName: "Imran Farooqi",
    department: "English Language And Literature",
    cnic: "42101-1000145-5",
    status: "Pending",
  },
  {
    serialNo: 133,
    studentName: "Asad Malik",
    fatherName: "Yasir Shah",
    department: "English Language And Literature",
    cnic: "42101-1000046-7",
    status: "Revert",
  },
  {
    serialNo: 134,
    studentName: "Naeem Malik",
    fatherName: "Muhammad Butt",
    department: "English Language And Literature",
    cnic: "42101-1000082-3",
    status: "Revert",
  },
  {
    serialNo: 135,
    studentName: "Danish Khan",
    fatherName: "Imran Butt",
    department: "English Language And Literature",
    cnic: "42101-1000105-5",
    status: "Pending",
  },
  {
    serialNo: 136,
    studentName: "Luqman Memon",
    fatherName: "Ameen Ansari",
    department: "Business Administration",
    cnic: "42101-1000038-9",
    status: "Trash",
  },
  {
    serialNo: 137,
    studentName: "Mohtashim Ansari",
    fatherName: "Shahid Rehman",
    department: "Business Administration",
    cnic: "42101-1000044-5",
    status: "Trash",
  },
  {
    serialNo: 138,
    studentName: "Aqib Raza",
    fatherName: "Ameen Khattak",
    department: "English Language And Literature",
    cnic: "42101-1000034-5",
    status: "Revert",
  },
  {
    serialNo: 139,
    studentName: "Sami Bhatti",
    fatherName: "Latif Mirza",
    department: "English Language And Literature",
    cnic: "42101-1000016-7",
    status: "Revert",
  },
  {
    serialNo: 140,
    studentName: "Bilal Mirza",
    fatherName: "Imran Memon",
    department: "Business Administration",
    cnic: "42101-1000133-3",
    status: "Pending",
  },
  {
    serialNo: 141,
    studentName: "Ali Ansari",
    fatherName: "Bilal Shaikh",
    department: "Business Administration",
    cnic: "42101-1000135-5",
    status: "Pending",
  },
  {
    serialNo: 142,
    studentName: "Naeem Zubair",
    fatherName: "Sajid Hashmi",
    department: "Business Administration",
    cnic: "42101-1000095-6",
    status: "Trash",
  },
  {
    serialNo: 143,
    studentName: "Tariq Bhatti",
    fatherName: "Ali Bhatti",
    department: "Business Administration",
    cnic: "42101-1000137-7",
    status: "Pending",
  },
  {
    serialNo: 144,
    studentName: "Fahad Mirza",
    fatherName: "Zafar Memon",
    department: "Business Administration",
    cnic: "42101-1000068-9",
    status: "Trash",
  },
  {
    serialNo: 145,
    studentName: "Asad Raza",
    fatherName: "Saleem Shaikh",
    department: "Computer Science",
    cnic: "42101-1000006-7",
    status: "Approved",
  },
  {
    serialNo: 146,
    studentName: "Bilal Chaudhry",
    fatherName: "Asad Hashmi",
    department: "Business Administration",
    cnic: "42101-1000119-9",
    status: "Pending",
  },
  {
    serialNo: 147,
    studentName: "Kamran Hussain",
    fatherName: "Danish Hashmi",
    department: "Business Administration",
    cnic: "42101-1000110-0",
    status: "Pending",
  },
  {
    serialNo: 148,
    studentName: "Danish Khattak",
    fatherName: "Yasir Memon",
    department: "Business Administration",
    cnic: "42101-1000026-7",
    status: "Trash",
  },
  {
    serialNo: 149,
    studentName: "Usman Memon",
    fatherName: "Sajid Rehman",
    department: "English Language And Literature",
    cnic: "42101-1000031-2",
    status: "Revert",
  },
  {
    serialNo: 150,
    studentName: "Ali Qureshi",
    fatherName: "Iftikhar Bhatti",
    department: "Computer Science",
    cnic: "42101-1000033-4",
    status: "Approved",
  },
  {
    serialNo: 151,
    studentName: "Kamran Khan",
    fatherName: "Hamza Khan",
    department: "English Language And Literature",
    cnic: "42101-1000115-5",
    status: "Pending",
  },
  {
    serialNo: 152,
    studentName: "Mohtashim Sheikh",
    fatherName: "Muhammad Shah",
    department: "Computer Science",
    cnic: "42101-1000027-8",
    status: "Approved",
  },
  {
    serialNo: 153,
    studentName: "Asad Zubair",
    fatherName: "Hafiz Memon",
    department: "English Language And Literature",
    cnic: "42101-1000019-0",
    status: "Revert",
  },
  {
    serialNo: 154,
    studentName: "Mohtashim Memon",
    fatherName: "Waqar Malik",
    department: "Business Administration",
    cnic: "42101-1000050-1",
    status: "Trash",
  },
  {
    serialNo: 155,
    studentName: "Tariq Farooqi",
    fatherName: "Usman Qureshi",
    department: "English Language And Literature",
    cnic: "42101-1000147-7",
    status: "Pending",
  },
  {
    serialNo: 156,
    studentName: "Sami Shaikh",
    fatherName: "Asad Butt",
    department: "Computer Science",
    cnic: "42101-1000138-8",
    status: "Pending",
  },
  {
    serialNo: 157,
    studentName: "Hassan Abbasi",
    fatherName: "Abdul Qureshi",
    department: "Business Administration",
    cnic: "42101-1000053-4",
    status: "Trash",
  },
  {
    serialNo: 158,
    studentName: "Noman Malik",
    fatherName: "Kamran Raza",
    department: "Business Administration",
    cnic: "42101-1000150-0",
    status: "Pending",
  },
  {
    serialNo: 159,
    studentName: "Hamza Khattak",
    fatherName: "Nisar Farooqi",
    department: "Business Administration",
    cnic: "42101-1000071-2",
    status: "Trash",
  },
  {
    serialNo: 160,
    studentName: "Asad Shaikh",
    fatherName: "Yasir Shaikh",
    department: "Computer Science",
    cnic: "42101-1000048-9",
    status: "Approved",
  },
  {
    serialNo: 161,
    studentName: "Ali Raza",
    fatherName: "Iftikhar Ansari",
    department: "English Language And Literature",
    cnic: "42101-1000052-3",
    status: "Revert",
  },
  {
    serialNo: 162,
    studentName: "Junaid Shaikh",
    fatherName: "Hassan Malik",
    department: "Computer Science",
    cnic: "42101-1000128-8",
    status: "Pending",
  },
  {
    serialNo: 163,
    studentName: "Ahmed Qureshi",
    fatherName: "Usman Chaudhry",
    department: "Computer Science",
    cnic: "42101-1000111-1",
    status: "Pending",
  },
  {
    serialNo: 164,
    studentName: "Tariq Malik",
    fatherName: "Usman Farooqi",
    department: "Business Administration",
    cnic: "42101-1000170-0",
    status: "Pending",
  },
  {
    serialNo: 165,
    studentName: "Usman Raza",
    fatherName: "Kamran Ansari",
    department: "English Language And Literature",
    cnic: "42101-1000156-6",
    status: "Pending",
  },
  {
    serialNo: 166,
    studentName: "Naeem Butt",
    fatherName: "Saleem Qureshi",
    department: "English Language And Literature",
    cnic: "42101-1000010-1",
    status: "Revert",
  },
  {
    serialNo: 167,
    studentName: "Danish Mirza",
    fatherName: "Noman Farooqi",
    department: "English Language And Literature",
    cnic: "42101-1000117-7",
    status: "Pending",
  },
  {
    serialNo: 168,
    studentName: "Hassan Rehman",
    fatherName: "Shahid Farooqi",
    department: "Business Administration",
    cnic: "42101-1000077-8",
    status: "Trash",
  },
  {
    serialNo: 169,
    studentName: "Usman Shaikh",
    fatherName: "Rashid Malik",
    department: "English Language And Literature",
    cnic: "42101-1000004-5",
    status: "Revert",
  },
  {
    serialNo: 170,
    studentName: "Hamza Mirza",
    fatherName: "Shahid Qureshi",
    department: "Computer Science",
    cnic: "42101-1000090-1",
    status: "Approved",
  },
  {
    serialNo: 171,
    studentName: "Usman Shaikh",
    fatherName: "Yasir Bhatti",
    department: "English Language And Literature",
    cnic: "42101-1000025-6",
    status: "Revert",
  },
];
